[package]
name = "git-cliff"
version = "0.3.0" # managed by release.sh
description = "A highly customizable changelog generator ⛰️"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
readme = "../README.md"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
categories = ["command-line-utilities"]
default-run = "git-cliff"
edition = "2018"

[[bin]]
name = "git-cliff-completions"
path = "src/bin/completions.rs"

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4.14"
dirs-next = "2.0.0"

[dependencies.git-cliff-core]
version = "0.3.0" # managed by release.sh
path = "../git-cliff-core"

[dependencies.structopt]
version = "0.3.23"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
pretty_assertions = "1.0.0"
