[package]
name = "git-cliff"
version = "1.0.9" # managed by release.sh
description = "A highly customizable changelog generator ⛰️"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
readme = "../README.md"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
categories = ["command-line-utilities"]
default-run = "git-cliff"
edition = "2021"
rust-version = "1.60.0"

[[bin]]
name = "git-cliff-completions"
path = "src/bin/completions.rs"

[[bin]]
name = "git-cliff-mangen"
path = "src/bin/mangen.rs"

[features]
# check for new versions
default = ["update-informer"]

[dependencies]
glob.workspace = true
regex.workspace = true
pretty_env_logger = "0.4.0"
log = "0.4.17"
dirs-next = "2.0.0"
clap_complete = "3.2.5"
clap_mangen = "0.1.11"

[dependencies.git-cliff-core]
version = "1.0.9" # managed by release.sh
path = "../git-cliff-core"

[dependencies.clap]
version = "3.2.22"
features = ["derive", "env", "wrap_help"]

[dependencies.update-informer]
version = "0.5.0"
optional = true

[dev-dependencies]
pretty_assertions = "1.2.1"
