[package]
name = "git-cliff"
version = "1.2.0" # managed by release.sh
description = "A highly customizable changelog generator ⛰️"
authors = ["git-cliff contributors <git-cliff@protonmail.com>"]
license = "GPL-3.0"
readme = "../README.md"
homepage = "https://github.com/orhun/git-cliff"
repository = "https://github.com/orhun/git-cliff"
keywords = ["changelog", "generator", "conventional", "commit"]
categories = ["command-line-utilities"]
default-run = "git-cliff"
edition = "2021"
rust-version = "1.64.0"

[[bin]]
name = "git-cliff-completions"
path = "src/bin/completions.rs"

[[bin]]
name = "git-cliff-mangen"
path = "src/bin/mangen.rs"

[features]
# check for new versions
default = ["update-informer"]

[dependencies]
glob.workspace = true
regex.workspace = true
log.workspace = true
pretty_env_logger = "0.5.0"
dirs-next = "2.0.0"
clap_complete = "4.3.2"
clap_mangen = "0.2.12"

[dependencies.git-cliff-core]
version = "1.2.0" # managed by release.sh
path = "../git-cliff-core"

[dependencies.clap]
version = "4.3.8"
features = ["derive", "env", "wrap_help", "cargo"]

[dependencies.update-informer]
version = "1.0.0"
optional = true

[dev-dependencies]
pretty_assertions = "1.2.1"

# metadata for cargo-binstall to get the right artifacts
[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ name }-{ version }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"
